name: Run Node.js Script

on:
  push:
    branches:
      - main  # Run the workflow on pushes to the main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18  # Use a specific Node.js version (e.g., 18.x)

    - name: Run the script
      run: |
        node main.js
